---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r}
library(flexdashboard)
library(p8105.datasets)
library(plotly)
library(tidyverse)
library(ggplot2)

data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Count the number of each department and show the bar plot.<br>

```{r}
instacart |> 
  count(department) |> 
  mutate(ndepartment = fct_reorder(department, n)) |> 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot shows the hourd the order has been placed in a day, seperating by product department

```{r}
instacart_1 = 
  instacart |>
  group_by(order_id)|>
  filter(add_to_cart_order == 1) |>
  mutate(department = fct_reorder(department, order_hour_of_day)) |> 
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box", colors = "viridis")
instacart_1
```

### Scatter plot shows total reorder numbers for different product departments.

```{r}
instacart_2 = 
  instacart |>
  group_by(department) |>
  mutate(reorder = sum(reordered),
         reorder = as.numeric(reorder)) |>
  distinct(department, reorder) |>
  plot_ly(
    x = ~department, y = ~reorder, 
    type = 'scatter', mode = 'markers', size = ~reorder,
    color = ~department)
instacart_2
```